var express = require('express');
var advancedUserGerRouter = express.Router();

/* GET Internet_Access page. */
advancedUserGerRouter.get('/', function(req, res) {
    res.render('./Advanced_User/Advanced_User', {
        title: 'Erweitert',
        ampimg: '/images/Search/AU_SearchThumb_ForDeveloper.jpg',
        headline: 'Für Entwickler',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Erweitert/">Erweitert</a></li>',
        canonical: '/Advanced_User/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Webseiten_Einbindung/', function(req, res) {
    res.render('./Advanced_User/Website_Integration', {
        title: 'Webseiten Einbindung',
        ampimg: '/images/Search/AU_SearchThumb_WebsiteIntegration.jpg',
        headline: 'IP Kamera Einbindung in die Webseite',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Webseiten_Einbindung/">Webseiten Einbindung</a></li>',
        canonical: '/Advanced_User/Website_Integration/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Webseiten_Einbindung/Cambozola', function(req, res) {
    res.render('./Advanced_User/Cambozola', {
        title: 'Cambozola (JAVA Plugin)',
        ampimg: '/images/Search/AU_SearchThumb_WebsiteIntegration_Cambozola.jpg',
        headline: 'Webseiten Einbindung mit Cambozola',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Webseiten_Einbindung/">Webseiten Einbindung</a></li><li><a href="/Erweitert/Webseiten_Einbindung/Cambozola/">Cambozola</a></li>',
        canonical: '/Advanced_User/Website_Integration/Cambozola/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Webseiten_Einbindung/Open_IP_Camera_Manager', function(req, res) {
    res.render('./Advanced_User/Open_IP_Camera_Manager', {
        title: 'Open IP Camera Manager (PHP)',
        ampimg: '/images/Search/AU_SearchThumb_WebsiteIntegration_OIPCM.jpg',
        headline: 'IP Camera Webseiten Einbindung with OICM',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Webseiten_Einbindung/">Webseiten Einbindung</a></li><li><a href="/Erweitert/Webseiten_Einbindung/Open_IP_Camera_Manager/">OIPCM</a></li>',
        canonical: '/Advanced_User/Website_Integration/Open_IP_Camera_Manager/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Webseiten_Einbindung/HD_Kamera_Einbindung', function(req, res) {
    res.render('./Advanced_User/HD_Camera_Integration', {
        title: 'HD Camera Webseiten Einbindung',
        ampimg: '/images/Search/AU_SearchThumb_WebsiteIntegration_HD_Cams.jpg',
        headline: 'H.264 IP Camera Webseiten Einbindung',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Webseiten_Einbindung/">Webseiten Einbindung</a></li><li><a href="/Erweitert/Webseiten_Einbindung/HD_Kamera_Einbindung/">HD Kameras</a></li>',
        canonical: '/Advanced_User/Website_Integration/HD_Camera_Integration/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/CGI_Befehle/', function(req, res) {
    res.render('./Advanced_User/CGI_Commands', {
        title: 'CGI Befehle',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'CGI Commands',
        breadcrumbs: '<li class="breadcrumb-item"><a href="/">Home</a></li><li class="breadcrumb-item"><a href="/Erweitert/">Erweitert</a></li><li class="breadcrumb-item"><a href="/Erweitert/CGI_Befehle/">CGI Befehle</a></li>',
        canonical: '/Advanced_User/CGI_Commands/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/CGI_Befehle/VGA_Serie_CGI_Befehle', function(req, res) {
    res.render('./Advanced_User/VGA_Series_CGI_List', {
        title: 'VGA Serie CGI Befehle',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands_VGA.jpg',
        breadcrumbs: '<li class="breadcrumb-item"><a href="/">Home</a></li><li class="breadcrumb-item"><a href="/Erweitert/">Erweitert</a></li><li class="breadcrumb-item"><a href="/Erweitert/CGI_Befehle/">CGI Befehle</a></li><li class="breadcrumb-item"><a href="/Erweitert/CGI_Befehle/VGA_Serie_CGI_Befehle/">VGA Serie</a></li>',
        canonical: '/Advanced_User/CGI_Commands/VGA_Series_CGI_List/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/', function(req, res) {
    res.render('./Advanced_User/Tasker', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker Android App</a></li>',
        canonical: '/Advanced_User/Tasker/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/Bewegungserkennung_Aufgabe_Hinzufuegen/', function(req, res) {
    res.render('./Advanced_User/Tasker_Motion_Detection_Add_Task', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Motion_Detection_Add_Task/">Bewegungserkennung - Aufgabe Hinzufügen</a></li>',
        canonical: '/Advanced_User/Tasker/Motion_Detection_Add_Task/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/Bewegungserkennung_Profil_Hinzufuegen/', function(req, res) {
    res.render('./Advanced_User/Tasker_Motion_Detection_Add_Profile', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Motion_Detection_Add_Profile/">Bewegungserkennung - Profil Hinzufügen</a></li>',
        canonical: '/Advanced_User/Tasker/Motion_Detection_Add_Profile/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/Bewegungserkennung_Deaktivieren_Aufgabe_Hinzufuegen/', function(req, res) {
    res.render('./Advanced_User/Tasker_Motion_Detection_Deactivate_Add_Task', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Motion_Detection_Deactivate_Add_Task/">Bewegungserkennung Deaktivieren - Aufgabe Hinzufügen</a></li>',
        canonical: '/Advanced_User/Tasker/Motion_Detection_Deactivate_Add_Task/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/Bewegungserkennung_Deaktivieren_Profil_Hinzufuegen/', function(req, res) {
    res.render('./Advanced_User/Tasker_Motion_Detection_Deactivate_Add_Profile', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Motion_Detection_Deactivate_Add_Profile/">Bewegungserkennung Deaktivieren - Profil Hinzufügen</a></li>',
        canonical: '/Advanced_User/Tasker/Motion_Detection_Deactivate_Add_Profile/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/IR_Aktivieren_Shortcut_Hinzufuegen/', function(req, res) {
    res.render('./Advanced_User/Tasker_IR_Add_Shortcut', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Activate_IR_Add_Shortcut/">IR Aktivieren - Shortcut Hinzufügen</a></li>',
        canonical: '/Advanced_User/Tasker/Activate_IR_Add_Shortcut/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/IR_Deaktivieren_Shortcut_Hinzufuegen/', function(req, res) {
    res.render('./Advanced_User/Tasker_IR_Deactivate_Add_Shortcut', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Deactivate_IR_Add_Shortcut/">IR Deaktivieren - Shortcut Hinzufügen</a></li>',
        canonical: '/Advanced_User/Tasker/Deactivate_IR_Add_Shortcut/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/Nachtsicht_Aktivieren_Aufgabe/', function(req, res) {
    res.render('./Advanced_User/Tasker_IR_Add_Task', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Activate_Nightvision_Task/">Nachtsicht Aktivieren</a></li>',
        canonical: '/Advanced_User/Tasker/Activate_Nightvision_Task/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/Nachtsicht_Deaktivieren_Aufgabe/', function(req, res) {
    res.render('./Advanced_User/Tasker_IR_Deactivate_Add_Task', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Deactivate_Nightvision_Task/">Nachtsicht Deaktivieren</a></li>',
        canonical: '/Advanced_User/Tasker/Deactivate_Nightvision_Task/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/Nachtsicht_Szene/', function(req, res) {
    res.render('./Advanced_User/Tasker_IR_Add_Scene', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Nightvision_Scene/">Nachtsicht Szene</a></li>',
        canonical: '/Advanced_User/Tasker/Nightvision_Scene/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/Zeitplan_PTZ_Aufgabe/', function(req, res) {
    res.render('./Advanced_User/Tasker_Schedule_Add_PTZ_Task', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Zeitplan_PTZ_Aufgabe/">Zeitplan PTZ Aufgabe</a></li>',
        canonical: '/Advanced_User/Tasker/Schedule_PTZ_Task/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/Zeitplan_Alarm_Aufgabe/', function(req, res) {
    res.render('./Advanced_User/Tasker_Schedule_Add_Alarm_Task', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Zeitplan_Alarm_Aufgabe/">Zeitplan Alarm Aufgabe</a></li>',
        canonical: '/Advanced_User/Tasker/Schedule_Alarm_Task/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Tasker/Zeitplan_Profil/', function(req, res) {
    res.render('./Advanced_User/Tasker_Schedule_Add_Profile', {
        title: 'Tasker Android App',
        ampimg: '/images/Search/AU_SearchThumb_CGICommands.jpg',
        headline: 'Makro Tools zum Automatisieren der Kamera Funktionen',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Tasker/">Tasker</a></li><li><a href="/Erweitert/Tasker/Zeitplan_Profil/">Zeitplan Profil</a></li>',
        canonical: '/Advanced_User/Tasker/Schedule_Profile/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/WebUI_Wiederherstellen/', function(req, res) {
    res.render('./Advanced_User/Restore_WebUI', {
        title: 'Wiederherstellen der WebUI nach einem fehlerhaften Update',
        ampimg: '/images/Search/AU_SearchThumb_ResetAfterWebUIError.jpg',
        headline: 'Wiederherstellen der WebUI nach einem fehlerhaften Update',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/WebUI_Wiederherstellen/">WebUI Wiederherstellen</a></li>',
        canonical: '/Advanced_User/Restore_WebUI/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Firmware_Wiederherstellen/', function(req, res) {
    res.render('./Advanced_User/Restore_Firmware', {
        title: 'Wiederherstellen der Firmware nach einem fehlerhaften Update',
        ampimg: '/images/Search/AU_SearchThumb_ResetAfterFirmwareError.jpg',
        headline: 'Wiederherstellen der Firmware nach einem fehlerhaften Update',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Firmware_Wiederherstellen/">Firmware Wiederherstellen</a></li>',
        canonical: '/Advanced_User/Restore_Firmware/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/Firmware_Wiederherstellen/VGA_Modelle', function(req, res) {
    res.render('./Advanced_User/Restore_Firmware_VGA', {
        title: 'Wiederherstellen der Firmware nach einem fehlerhaften Update',
        ampimg: '/images/Search/AU_SearchThumb_ResetAfterFirmwareError.jpg',
        headline: 'Wiederherstellen der Firmware nach einem fehlerhaften Update',
        breadcrumbs: '<li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/Firmware_Wiederherstellen/">Firmware Wiederherstellen</a></li><li><a href="/Erweitert/Firmware_Wiederherstellen/VGA_Modelle/">VGA Modelle</a></li>',
        canonical: '/Advanced_User/Restore_Firmware/VGA_Models',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/CCTV_vs_IP/', function(req, res) {
    res.render('./Advanced_User/CCTV_vs_IP', {
        title: 'Unterschied zwischen Analog und IP Kameras',
        ampimg: '/images/Search/AU_SearchThumb_IPvsCCTV.jpg',
        headline: 'Unterschied zwischen Analog und IP Kameras',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/CCTV_vs_IP/">CCTV vs IP</a></li>',
        canonical: '/Advanced_User/CCTV_vs_IP/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

advancedUserGerRouter.get('/VPN_AVM_Fritzbox/', function(req, res) {
    res.render('./Advanced_User/VPN_AVM_Fritzbox_Windows', {
        title: 'VPN in AVM Fritzbox',
        ampimg: '/images/Search/AU_SearchThumb_VPN.jpg',
        headline: 'IP Camera Webseiten Einbindung',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Erweitert/">Erweitert</a></li><li><a href="/Erweitert/VPN_AVM_Fritzbox/">VPN AVM Fritzbox</a></li>',
        canonical: '/Advanced_User/VPN_AVM_Fritzbox/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: '',
    		mdtab: 'hidden',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: 'expanded',
    		autab: '',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

module.exports = advancedUserGerRouter;
