var express = require('express');
var motionDetectionGerRouter = express.Router();

/* GET Internet_Access page. */
motionDetectionGerRouter.get('/', function(req, res) {
    res.render('./Motion_Detection/Motion_Detection', {
        title: 'Bewegungserkennung und Alarmbenachrichtigung',
        ampimg: '/images/Search/MD_SearchThumb_MotionDetection.jpg',
        headline: 'Bewegungserkennung und Alarmbenachrichtigung - nutzen Sie den integrierten Bildvergleich um Bewegungen vor der Kamera zu erkennne und Alarmaktionen auszulösen',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li>',
        canonical: '/Motion_Detection/',
        description: 'Der integrierte, softwarebasierten Bildvergleich ermöglicht das Erkennen von Bewegungen vor der Kamera. Legen Sie hier bis zu 4 Erkennungsbereiche und Empfindlichkeiten fest um bei Alarm Aktionen wie die Email- und Push-Benachrichtigung, Alarmvideoaufnahme auf SD-Karte oder einen Cloud Upload auszulösen.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Einrichtung/', function(req, res) {
    res.render('./Motion_Detection/Motion_Detection_Setup', {
        title: 'INSTAR Full HD Kameras - Bewegungserkennung Einrichtung',
        ampimg: '/images/Search/MD_SearchThumb_MDSetup_1080p.jpg',
        headline: 'Aktivieren der Bewegungserkennung bei Ihrer INSTAR 1080p Überwachungskamera über 4 Alarmbereiche und Auswahl der Alarmaktionen.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Einrichtung/">Einrichtung</a></li>',
        canonical: '/Motion_Detection/Setup/',
        description: 'Zeichnen Sie bis zu 4 Alarmbereiche ein und vergeben Sie eine Sensitivität für die Bewegungserkennung. Legen Sie danach fest, wie die Kamera bei Alarm reagieren soll - Alarm-Videoaufnahme auf die interne SD Karte, Emailversand mit Bildanhang, Pushbenachrichtigung auf Ihr Handy sowie Alarm Video-Uploads auf FTP Server oder in die INSTAR Cloud. Um Fehlalarme zu vermeiden, empfiehlt es sich den integrierten PIR Sensor mit der softwarebasierten Bewegungserkennung zu koppeln. Für die Kameramodelle IN-9008 Full HD, IN-8015 Full HD und IN-9020 Full HD.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Einrichtung/720p_Serie/', function(req, res) {
    res.render('./Motion_Detection/Motion_Detection_Setup_720p', {
        title: 'INSTAR HD Kameras - Bewegungserkennung Einrichtung',
        ampimg: '/images/Search/MD_SearchThumb_MDSetup_720p.jpg',
        headline: 'Aktivieren der Bewegungserkennung bei Ihrer INSTAR 720p Überwachungskamera über 4 Alarmbereiche und Auswahl der Alarmaktionen.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Einrichtung/">Einrichtung</a></li><li><a href="/Bewegungserkennung/Einrichtung/720p_Serie/">720p Serie</a></li>',
        canonical: '/Motion_Detection/Setup/720p_Series/',
        description: 'Zeichnen Sie bis zu 4 Alarmbereiche ein und vergeben Sie eine Sensitivität für die Bewegungserkennung. Legen Sie danach fest, wie die Kamera bei Alarm reagieren soll - Alarm-Videoaufnahme auf die interne SD Karte, Emailversand mit Bildanhang, Pushbenachrichtigung auf Ihr Handy sowie Alarm Video-Uploads auf FTP Server oder in die INSTAR Cloud. Um Fehlalarme zu vermeiden, empfiehlt es sich den integrierten PIR Sensor (falls vorhanden) mit der softwarebasierten Bewegungserkennung zu koppeln. Für die Kameramodelle IN-7011 HD, IN-6014 HD, IN-6012 HD, IN-6001 HD, IN-5907 HD und IN-5905 HD.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Einrichtung/VGA_Serie/', function(req, res) {
    res.render('./Motion_Detection/Motion_Detection_Setup_VGA', {
        title: 'INSTAR VGA Kameras - Bewegungserkennung Einrichtung',
        ampimg: '/images/Search/MD_SearchThumb_MDSetup_VGA.jpg',
        headline: 'Aktivieren der Bewegungserkennung bei Ihrer INSTAR VGA Überwachungskamera und wählen Sie Alarmaktionen.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Einrichtung/">Einrichtung</a></li><li><a href="/Bewegungserkennung/Einrichtung/VGA_Serie/">VGA Serie</a></li>',
        canonical: '/Motion_Detection/Setup/VGA_Series/',
        description: 'Aktivieren Sie die Bewegungserkennung und legen Sie die gewünschten Alarmaktionen fest - Emailversand, FTP Upload oder eine Pushbenachrichtigung auf Ihr Handy. Für die Kameramodelle IN-3011, IN-3010, IN-3001, IN-2908, IN-2907 und IN-2905.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Alarmbenachrichtigung/', function(req, res) {
    res.render('./Motion_Detection/Alarm_Notification', {
        title: 'INSTAR Full HD Kameras - Alarmbenachrichtigung über Emailversand',
        ampimg: '/images/Search/MD_SearchThumb_AlarmNotification_1080p.jpg',
        headline: 'Für das Versenden einer Alarm-Email müssen Sie in der INSTAR 1080p Sicherheitskamera einen SMTP Email-Ausgangserver hinterlegen. Lernen Sie hier wie.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Alarmbenachrichtigung/">Alarmbenachrichtigung</a></li>',
        canonical: '/Motion_Detection/Alarm_Notification/',
        description: 'Hinterlegen Sie hier den SMTP Server Ihres Email Anbieters in Ihrer INSTAR Full HD Kamera, um bei einer Bewegungserkennung per Email und Snapshot Anhang benachrichtigt zu werden. Sollte Ihnen der Email-Ausgangserver Ihres Anbieters nicht bekannt sein, können Sie einfach den INSTAR SMTP Server aus der Vorauswahl nutzen um Emails an Ihre persönliche Email Adresse senden zu lassen. Für die Kameramodelle IN-9008 Full HD, IN-8015 Full HD und IN-9020 Full HD.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Alarmbenachrichtigung/720p_Serie/', function(req, res) {
    res.render('./Motion_Detection/Alarm_Notification_720p', {
        title: 'INSTAR HD Kameras - Alarmbenachrichtigung über Emailversand',
        ampimg: '/images/Search/MD_SearchThumb_AlarmNotification_720p.jpg',
        headline: 'Für das Versenden einer Alarm-Email müssen Sie in der INSTAR 720p Sicherheitskamera einen SMTP Email-Ausgangserver hinterlegen. Lernen Sie hier wie.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Alarmbenachrichtigung/">Alarmbenachrichtigung</a></li><li><a href="/Bewegungserkennung/Alarmbenachrichtigung/720p_Serie/">720p Serie</a></li>',
        canonical: '/Motion_Detection/Alarm_Notification/720p_Series/',
        description: 'Hinterlegen Sie hier den SMTP Server Ihres Email Anbieters in Ihrer INSTAR HD Kamera, um bei einer Bewegungserkennung per Email und Snapshot Anhang benachrichtigt zu werden. Sollte Ihnen der Email-Ausgangserver Ihres Anbieters nicht bekannt sein, können Sie einfach den INSTAR SMTP Server aus der Vorauswahl nutzen um Emails an Ihre persönliche Email Adresse senden zu lassen. Für die Kameramodelle IN-7011 HD, IN-6014 HD, IN-6012 HD, IN-6001 HD, IN-5907 HD und IN-5905 HD.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Alarmbenachrichtigung/VGA_Serie/', function(req, res) {
    res.render('./Motion_Detection/Alarm_Notification_VGA', {
        title: 'INSTAR VGA Kameras - Alarmbenachrichtigung über Emailversand',
        ampimg: '/images/Search/MD_SearchThumb_AlarmNotification_VGA.jpg',
        headline: 'Für das Versenden einer Alarm-Email müssen Sie in der INSTAR VGA Sicherheitskamera einen SMTP Email-Ausgangserver hinterlegen. Lernen Sie hier wie.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Alarmbenachrichtigung/">Alarmbenachrichtigung</a></li><li><a href="/Bewegungserkennung/Alarmbenachrichtigung/VGA_Serie/">VGA Serie</a></li>',
        canonical: '/Motion_Detection/Alarm_Notification/VGA_Series/',
        description: 'Hinterlegen Sie hier den SMTP Server Ihres Email Anbieters in Ihrer INSTAR VGA Kamera, um bei einer Bewegungserkennung per Email und Snapshot Anhang benachrichtigt zu werden. Sollte Ihnen der Email-Ausgangserver Ihres Anbieters nicht bekannt sein, können Sie einfach den INSTAR SMTP Server nutzen um Emails an Ihre persönliche Email Adresse senden zu lassen. Für die Kameramodelle IN-3011, IN-3010, IN-3001, IN-2908, IN-2907 und IN-2905.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Alarmbenachrichtigung/Fehlerbehebung/', function(req, res) {
    res.render('./Motion_Detection/Alarm_Notification_Troubles', {
        title: 'Alarmbenachrichtigung - Fehlerbehebung für den Emailversand',
        ampimg: '/images/Search/MD_SearchThumb_AlarmNotification_Troubleshooting.jpg',
        headline: 'Email Troubleshooting - lesen Sie hier weiter, wenn Ihnen Ihre INSTAR Sicherheitskamera bei Alarm keine Emails sendet.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Alarmbenachrichtigung/">Alarmbenachrichtigung</a></li><li><a href="/Bewegungserkennung/Alarmbenachrichtigung/Fehlerbehebung/">Fehlerbehebung</a></li>',
        canonical: '/Motion_Detection/Alarm_Notification/Troubleshooting/',
        description: 'Troubleshooting - Email Versand. Wenn der Email Versand bei Alarm, oder bereits die Test Email bei den Emaileinstellungen Ihrer INSTAR Webcam, nicht klappt, lesen Sie hier weiter, um dem Problem auf den Grund zu gehen.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Alarmbenachrichtigung/SMTP_Server', function(req, res) {
    res.render('./Motion_Detection/Alarm_Notification_SMTP_Servers', {
        title: 'SMTP Server',
        ampimg: '/images/Search/MD_SearchThumb_AlarmNotification.jpg',
        headline: 'Alarmbenachrichtigung - SMTP Server der gängigsten, kostenlosen Email-Anbieter.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Alarmbenachrichtigung/">Alarmbenachrichtigung</a></li><li><a href="/Bewegungserkennung/Alarmbenachrichtigung/SMTP_Server/">SMTP Server</a></li>',
        canonical: '/Motion_Detection/Alarm_Notification/SMTP_Servers/',
        description: 'Sie finden hier eine Liste der Email-Ausgangserver der gängigsten kostenlosen Email Anbieter, die Sie für den Versand von Alarm-Emails für Ihre INSTAR Sicherheitskamera verwenden können.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Alarm_Aufnahme/', function(req, res) {
    res.render('./Motion_Detection/Alarm_Recording', {
        title: 'Videoaufnahme bei Ihrer INSTAR Überwachungskamera',
        ampimg: '/images/Search/MD_SearchThumb_AlarmRecording.jpg',
        headline: 'Starten Sie manuell eine Aufnahme oder legen Sie einen Zeitplan fest, innerhalb dessen die Kamera Videos auf die interne SD Karte aufnehmen soll.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Alarm_Aufnahme/">Alarm Aufnahme</a></li>',
        canonical: '/Motion_Detection/Alarm_Recording/',
        description: 'Neben der, durch die Bewegungserkennung ausgelösten, Alarmaufnahme bei Ihrer INSTAR IP Kamera, können Sie auch manuell eine Videoaufnahme auf die interne SD Karte starten, oder einen Zeitplan festlegen, innerhalb dessen eine geplante Aufnahme angefertigt werden soll.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/SD_Karten_Zugriff/', function(req, res) {
    res.render('./Motion_Detection/SD_Card_Access', {
        title: 'SD Karten Zugriff bei Ihrer INSTAR Netzwerkkamera',
        ampimg: '/images/Search/MD_SearchThumb_SDCardAccess.jpg',
        headline: 'Lernen Sie hier, wie Sie auf Ihre Video- und Fotoaufnahmen auf der internen SD Karte zugreifen können.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/">SD Karten Zugriff</a></li>',
        canonical: '/Motion_Detection/SD_Card_Access/',
        description: 'Alle gespeicherten Videos und Schnappschüsse werden von Ihrer INSTAR Netzwerkkamera auf der internen SD Karten gespeichert. Lernen Sie hier, wie Sie über den Webbrowser, mit dem INSTAR Kamera Tool oder einer unserer Handy Apps - InstarVision für Android, iOS, Windows und Windows Phone - auf Ihre Aufnahmen zugreifen können.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/SD_Karten_Zugriff/Bitkinex/', function(req, res) {
    res.render('./Motion_Detection/SD_Card_Access_Bitkinex', {
        title: 'SD Karten Zugriff - Bitkinex',
        ampimg: '/images/Search/MD_SearchThumb_SDCardAccess_Bitkinex.jpg',
        headline: 'SD Karten Zugriff mit der FTP Software Bitkinex.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/">SD Karten Zugriff</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/Bitkinex/">Bitkinex</a></li>',
        canonical: '/Motion_Detection/SD_Card_Access/Bitkinex/',
        description: 'Wenn Sie das INSTAR Kamera Tool oder die InstarVision Handy App für Android, iOS, Blackberry, Windows und Windows Phone nicht nutzen möchten, können Sie auch eine Drittanbieter Software, wie die FTP Software Bitkinex verwenden.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/SD_Karten_Zugriff/CuteFTP', function(req, res) {
    res.render('./Motion_Detection/SD_Card_Access_CuteFTP', {
        title: 'SD Karten Zugriff - CuteFTP',
        ampimg: '/images/Search/MD_SearchThumb_SDCardAccess_CuteFTP.jpg',
        headline: 'SD Karten Zugriff mit der FTP Software CuteFTP',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/">SD Karten Zugriff</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/CuteFTP/">CuteFTP</a></li>',
        canonical: '/Motion_Detection/SD_Card_Access/CuteFTP/',
        description: 'Wenn Sie das INSTAR Kamera Tool oder die InstarVision Handy App für Android, iOS, Blackberry, Windows und Windows Phone nicht nutzen möchten, können Sie auch eine Drittanbieter Software, wie die FTP Software CuteFTP verwenden.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/SD_Karten_Zugriff/DownThemAll', function(req, res) {
    res.render('./Motion_Detection/SD_Card_Access_DownThemAll', {
        title: 'SD Karten Zugriff - DownThemAll',
        ampimg: '/images/Search/MD_SearchThumb_SDCardAccess_DTA.jpg',
        headline: 'SD Karten Zugriff mit dem Firefox Browserplugin DownThemAll',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/">SD Karten Zugriff</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/DownThemAll/">DownThemAll</a></li>',
        canonical: '/Motion_Detection/SD_Card_Access/DownThemAll/',
        description: 'Wenn Sie das INSTAR Kamera Tool oder die InstarVision Handy App für Android, iOS, Blackberry, Windows und Windows Phone nicht nutzen möchten, können Sie auch eine Drittanbieter Software, wie das Firefox Plugin DownThemAll verwenden.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/SD_Karten_Zugriff/Interachy', function(req, res) {
    res.render('./Motion_Detection/SD_Card_Access_Interarchy', {
        title: 'SD Karten Zugriff - Interachy',
        ampimg: '/images/Search/MD_SearchThumb_SDCardAccess_Interachy.jpg',
        headline: 'SD Karten Zugriff mit der FTP Software Interachy',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/">SD Karten Zugriff</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/Interachy/">Interachy</a></li>',
        canonical: '/Motion_Detection/SD_Card_Access/Interachy/',
        description: 'Wenn Sie das INSTAR Kamera Tool oder die InstarVision Handy App für Android, iOS, Blackberry, Windows und Windows Phone nicht nutzen möchten, können Sie auch eine Drittanbieter Software, wie die FTP Software Interachy verwenden.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/SD_Karten_Zugriff/DeepVacuum', function(req, res) {
    res.render('./Motion_Detection/SD_Card_Access_DeepVacuum', {
        title: 'SD Karten Zugriff - DeepVacuum',
        ampimg: '/images/Search/MD_SearchThumb_SDCardAccess_DeepVacuum.jpg',
        headline: 'SD Karten Zugriff mit der FTP Software DeepVacuum',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/">SD Karten Zugriff</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/DeepVacuum/">DeepVacuum</a></li>',
        canonical: '/Motion_Detection/SD_Card_Access/DeepVacuum/',
        description: 'Wenn Sie das INSTAR Kamera Tool oder die InstarVision Handy App für Android, iOS, Blackberry, Windows und Windows Phone nicht nutzen möchten, können Sie auch eine Drittanbieter Software, wie die FTP Software DeepVacuum verwenden.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/SD_Karten_Zugriff/SiteSucker', function(req, res) {
    res.render('./Motion_Detection/SD_Card_Access_SiteSucker', {
        title: 'SD Karten Zugriff - SiteSucker',
        ampimg: '/images/Search/MD_SearchThumb_SDCardAccess_SiteSucker.jpg',
        headline: 'SD Karten Zugriff mit der FTP Software SiteSucker',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/">SD Karten Zugriff</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/SiteSucker/">SiteSucker</a></li>',
        canonical: '/Motion_Detection/SD_Card_Access/SiteSucker/',
        description: 'Wenn Sie das INSTAR Kamera Tool oder die InstarVision Handy App für Android, iOS, Blackberry, Windows und Windows Phone nicht nutzen möchten, können Sie auch eine Drittanbieter Software, wie die FTP Software SiteSucker verwenden.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/SD_Karten_Zugriff/SimpleWget', function(req, res) {
    res.render('./Motion_Detection/SD_Card_Access_SimpleWget', {
        title: 'SD Karten Zugriff - SimpleWget',
        ampimg: '/images/Search/MD_SearchThumb_SDCardAccess_SimpleWget.jpg',
        headline: 'SD Karten Zugriff mit der FTP Software SimpleWget',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/">SD Karten Zugriff</a></li><li><a href="/Bewegungserkennung/SD_Karten_Zugriff/SimpleWget/">SimpleWget</a></li>',
        canonical: '/Motion_Detection/SD_Card_Access/SimpleWget/',
        description: 'Wenn Sie das INSTAR Kamera Tool oder die InstarVision Handy App für Android, iOS, Blackberry, Windows und Windows Phone nicht nutzen möchten, können Sie auch eine Drittanbieter Software, wie die FTP Software SimpleWget verwenden.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Alarm_FTP_Upload/', function(req, res) {
    res.render('./Motion_Detection/Alarm_FTP_Upload', {
        title: 'INSTAR Full HD Kameras - Alarm und geplanter FTP Upload',
        ampimg: '/images/Search/MD_SearchThumb_FTPSettingsAlarmUpload_1080p.jpg',
        headline: 'Einrichten der FTP Einstellungen für Alarm und Fotoserie Uploads bei Ihrer INSTAR 1080p Netzwerkkamera.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Alarm_FTP_Upload/">Alarm FTP Upload</a></li>',
        canonical: '/Motion_Detection/Alarm_FTP_Upload/',
        description: 'Neben der Aufnahme auf die interne SD Karte haben Sie bei einer INSTAR IP Kamera die Möglichkeit Videoaufnahmen und Einzelbilder im Alarmfall oder per Zeitplan auf einen FTP Server hochzuladen. Nutzen Sie diese Funktion um Dateien zu sichern oder Bildmaterial in Ihre Webseite einzubinden. Lesen Sie weiter für die weitere FTP Konfiguration Ihrer Überwachung- oder Wetterkamera. Für die Kameramodelle IN-9008 Full HD, IN-8015 Full HD und IN-9020 Full HD.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Alarm_FTP_Upload/720p_Serie/', function(req, res) {
    res.render('./Motion_Detection/Alarm_FTP_Upload_720p', {
        title: 'INSTAR HD Kameras - Alarm und geplanter FTP Upload',
        ampimg: '/images/Search/MD_SearchThumb_FTPSettingsAlarmUpload_720p.jpg',
        headline: 'Einrichten der FTP Einstellungen für Alarm und Fotoserie Uploads bei Ihrer INSTAR 720p Netzwerkkamera.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Alarm_FTP_Upload/">Alarm FTP Upload</a></li><li><a href="/Bewegungserkennung/Alarm_FTP_Upload/720p_Serie/">720p Serie</a></li>',
        canonical: '/Motion_Detection/Alarm_FTP_Upload/720p_Series/',
        description: 'Neben der Aufnahme auf die interne SD Karte haben Sie bei einer INSTAR IP Kamera die Möglichkeit Videoaufnahmen und Einzelbilder im Alarmfall oder per Zeitplan auf einen FTP Server hochzuladen. Nutzen Sie diese Funktion um Dateien zu sichern oder Bildmaterial in Ihre Webseite einzubinden. Lesen Sie weiter für die weitere FTP Konfiguration Ihrer Überwachung- oder Wetterkamera. Für die Kameramodelle IN-7011 HD, IN-6014 HD, IN-6012 HD, IN-6001 HD, IN-5907 HD und IN-5905 HD.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Alarm_FTP_Upload/VGA_Serie/', function(req, res) {
    res.render('./Motion_Detection/Alarm_FTP_Upload_VGA', {
        title: 'INSTAR VGA Kameras - Alarm und geplanter FTP Upload',
        ampimg: '/images/Search/MD_SearchThumb_FTPSettingsAlarmUpload_VGA.jpg',
        headline: 'Einrichten der FTP Einstellungen für Alarm und Fotoserie Uploads bei Ihrer INSTAR VGA Netzwerkkamera.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Alarm_FTP_Upload/">Alarm FTP Upload</a></li><li><a href="/Bewegungserkennung/Alarm_FTP_Upload/VGA_Series/">VGA Serie</a></li>',
        canonical: '/Motion_Detection/Alarm_FTP_Upload/VGA_Series/',
        description: 'Sie haben bei einer INSTAR IP Kamera die Möglichkeit Videoaufnahmen und Einzelbilder im Alarmfall oder per Zeitplan auf einen FTP Server hochzuladen. Nutzen Sie diese Funktion um Dateien zu sichern oder Bildmaterial in Ihre Webseite einzubinden. Lesen Sie weiter für die weitere FTP Konfiguration Ihrer Überwachung- oder Wetterkamera. Für die Kameramodelle IN-3011, IN-3010, IN-3001, IN-2908, IN-2907 und IN-2905.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Router_als_FTP_Server/', function(req, res) {
    res.render('./Motion_Detection/Router_as_a_FTP_Server', {
        title: 'Router oder NAS als FTP Server für Ihre INSTAR Netzwerkkamera',
        ampimg: '/images/Search/MD_SearchThumb_RouterAsFTPServer.jpg',
        headline: 'Richten Sie Ihren Router oder NAS als FTP Server für Ihre INSTAR Überwachungskamera ein.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/">Router als FTP Server</a></li>',
        canonical: '/Motion_Detection/Router_as_a_FTP_Server/',
        description: 'Sichern Sie Alarmaufnahmen und geplante Zeitraffer-Fotoserien auf dem lokalen FTP Server Ihres Routers oder NAS. Die Videoaufnahmen liegen damit sicher auf einem Datenträger in Ihrer Wohnung, sollte die Sicherheitskamera, zusammen mit der internen SD Karte, gestohlen oder beschädigt werden.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Router_als_FTP_Server/AVM_Fritzbox_als_FTP_Server', function(req, res) {
    res.render('./Motion_Detection/AVM_Fritzbox_as_FTP_Server', {
        title: 'AVM Fritzbox als FTP Server für Ihre INSTAR Netzwerkkamera',
        ampimg: '/images/Search/MD_SearchThumb_RouterAsFTPServer_Fritzbox.jpg',
        headline: 'Richten Sie Ihre AVM Fritzbox als FTP Server für Ihre INSTAR Überwachungskamera ein.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/">Router als FTP Server</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/AVM_Fritzbox_als_FTP_Server/">AVM Fritzbox</a></li>',
        canonical: '/Motion_Detection/Router_as_a_FTP_Server/AVM_Fritzbox_as_FTP_Server/',
        description: 'Schließen Sie einen USB Datenträger an Ihrer AVM Fritzbox an. Kofigurieren Sie Ihre INSTAR Netzwerkkamera um Alarmvideos und geplante Aufnahmen per FTP auf Ihr Fritz!NAS zu laden. Lesen Sie weiter für eine Schritt-für-Schritt Konfigurationsanleitung.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Router_als_FTP_Server/Telekom_Speedport_als_FTP_Server', function(req, res) {
    res.render('./Motion_Detection/Telekom_Speedport_as_FTP_Server', {
        title: 'Telekom Speedport als FTP Server für Ihre INSTAR Netzwerkkamera',
        ampimg: '/images/Search/MD_SearchThumb_RouterAsFTPServer_Speedport.jpg',
        headline: 'Richten Sie Ihren Telekom Speedport als FTP Server für Ihre INSTAR Überwachungskamera ein.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/">Router als FTP Server</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/Telekom_Speedport_als_FTP_Server/">Speedport</a></li>',
        canonical: '/Motion_Detection/Router_as_a_FTP_Server/Telekom_Speedport_as_FTP_Server/',
        description: 'Schließen Sie einen USB Datenträger an Ihrer Telekom Speedport an. Kofigurieren Sie Ihre INSTAR Netzwerkkamera um Alarmvideos und geplante Aufnahmen per FTP auf den USB Stick zu laden. Lesen Sie weiter für eine Schritt-für-Schritt Konfigurationsanleitung.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Router_als_FTP_Server/QNAP_als_FTP_Server', function(req, res) {
    res.render('./Motion_Detection/QNAP_as_FTP_Server', {
        title: 'QNAP als FTP Server für Ihre INSTAR Netzwerkkamera',
        ampimg: '/images/Search/MD_SearchThumb_RouterAsFTPServer_QNAP.jpg',
        headline: 'Richten Sie Ihr QNAP Netzlaufwerk (NAS) als FTP Server für Ihre INSTAR Überwachungskamera ein.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/">Router als FTP Server</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/QNAP_als_FTP_Server/">QNAP</a></li>',
        canonical: '/Motion_Detection/Router_as_a_FTP_Server/QNAP_as_FTP_Server/',
        description: 'QNAP Netzlaufwerke wie die Modelle QNAP TS-251+, QNAP TS-453A und QNAP TS-253A, bieten neben der Surveillance Station Software auch noch einen einfachen FTP Dienst an, über den Sie Ihre Alarm-Videoaufnahme und Fotoserien Ihrer INSTAR Webcam sichern können. Lesen Sie weiter für eine Schritt-für-Schritt Konfigurationsanleitung.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Router_als_FTP_Server/Synology_als_FTP_Server', function(req, res) {
    res.render('./Motion_Detection/Synology_as_FTP_Server', {
        title: 'Synology als FTP Server für Ihre INSTAR Netzwerkkamera',
        ampimg: '/images/Search/MD_SearchThumb_RouterAsFTPServer_Synology.jpg',
        headline: 'Richten Sie Ihr Synology Netzlaufwerk (NAS) als FTP Server für Ihre INSTAR Überwachungskamera ein.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/">Router als FTP Server</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/Synology_als_FTP_Server/">Synology</a></li>',
        canonical: '/Motion_Detection/Router_as_a_FTP_Server/Synology_as_FTP_Server/',
        description: 'Synology Netzlaufwerke wie die Modelle Synology DS216j, Synology DS115J und Synology Diskstation DS213j, bieten neben der Surveillance Station Software auch noch einen einfachen FTP Dienst an, über den Sie Ihre Alarm-Videoaufnahme und Fotoserien Ihrer INSTAR Webcam sichern können. Lesen Sie weiter für eine Schritt-für-Schritt Konfigurationsanleitung.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Router_als_FTP_Server/WD_MyCloud_als_FTP_Server', function(req, res) {
    res.render('./Motion_Detection/WD_MyCloud_as_FTP_Server', {
        title: 'Western Digital MyCloud als FTP Server für Ihre INSTAR Netzwerkkamera',
        ampimg: '/images/Search/MD_SearchThumb_RouterAsFTPServer_WD.jpg',
        headline: 'Richten Sie Ihr Western Digital MyCloud Netzlaufwerk (NAS) als FTP Server für Ihre INSTAR Überwachungskamera ein.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/">Router als FTP Server</a></li><li><a href="/Bewegungserkennung/Router_als_FTP_Server/WD_MyCloud_als_FTP_Server/">WD MyCloud</a></li>',
        canonical: '/Motion_Detection/Router_as_a_FTP_Server/WD_MyCloud_as_FTP_Server/',
        description: 'Netzlaufwerke wie die Western Digital My Cloud persönliche Cloud NAS Festplatte, bieten einen einfachen FTP Dienst an, über den Sie Ihre Alarm-Videoaufnahme und Fotoserien Ihrer INSTAR Webcam sichern können. Lesen Sie weiter für eine Schritt-für-Schritt Konfigurationsanleitung.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/FTP_Server_Setup/', function(req, res) {
    res.render('./Motion_Detection/FTP_Server_Setup', {
        title: 'FTP Server Setup - Filezilla Server für Ihre INSTAR Sicherheitskamera',
        ampimg: '/images/Search/MD_SearchThumb_FTPServerSetup.jpg',
        headline: 'Filezilla Server ermöglicht Ihnen das Aufsetzen eines einfachen FTP Servers auf Ihrem Windows PC, den Sie zum Sichern der Alarm-Videoaufnahme Ihrer INSTAR Überwachungskamera nutzen können.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/FTP_Server_Setup/">FTP Server Setup</a></li>',
        canonical: '/Motion_Detection/FTP_Server_Setup/',
        description: 'Der Filezilla Server ist eine einfacher FTP Server, den Sie auf Ihrem Windows PC installieren und zusammen mit Ihrer INSTAR Netzwerkkamera nutzen können. Laden Sie Alarmvideos oder aufgenommene Fotoserien auf den FTP Server hoch und stellen Sie damit sicher, das Ihnen nie eine Aufnahme abhanden kommt - auch wenn die Überwachungskamera gestohlen, oder die interne SD Karte beschädigt werden sollte.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/FTP_Server_Setup/Install_FileZilla_Server/', function(req, res) {
    res.render('./Motion_Detection/Install_FileZilla_Server', {
        title: 'FTP Filezilla Server Setup',
        ampimg: '/images/Search/MD_SearchThumb_FTPServerSetup.jpg',
        headline: 'FTP Filezilla Server Setup',
        breadcrumbs: '<li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/FTP_Server_Setup/">FTP Server Setup</a></li><li><a href="/Bewegungserkennung/FTP_Server_Setup/Install_FileZilla_Server/">Filezilla Installation</a></li>',
        canonical: '/Motion_Detection/FTP_Server_Setup/Install_FileZilla_Server/',
        description: 'INSTAR Wiki - IP Kamera Wissensdatenbank',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/Alarm_Server/', function(req, res) {
    res.render('./Motion_Detection/Alarm_Server', {
        title: 'Alarm Server Funktion für die Einbindung in Hausautomatisierungen wie FHEM',
        ampimg: '/images/Search/MD_SearchThumb_AlarmServer.jpg',
        headline: 'Der Alarm Server sendet einen HTTP GET Befehl an eine IP in Ihrem Netzwerk.',
        breadcrumbs: '<li><a href="/">Home</a></li><li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/Alarm_Server/">Alarm Server</a></li>',
        canonical: '/Motion_Detection/Alarm_Server/',
        description: 'Entwickler können den Alarmserver der INSTAR Überwachungskamera nutzen, um im Alarmfall einen Befehl über das Netzwerk an eine Hausautomatisierungen wie z.B. FHEM zu senden. Koppeln Sie so die Bewegungserkennung Ihrer Webcam mit Aktionen die Ihr Smart Home ausführen kann.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/INSTAR_Cloud/', function(req, res) {
    res.render('./Motion_Detection/Cloud', {
        title: 'INSTAR Cloud für Ihre INSTAR Sicherheitskamera',
        ampimg: '/images/Search/MD_SearchThumb_Cloud.jpg',
        headline: 'INSTAR Cloud - ein Überblick über die neue Online Aufnahmeplattform für IP Kameras von INSTAR',
        breadcrumbs: '<li class="breadcrumb-item"><a href="/">Home</a></li><li class="breadcrumb-item"><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li class="breadcrumb-item"><a href="/Bewegungserkennung/INSTAR_Cloud/">INSTAR Cloud</a></li>',
        canonical: '/Motion_Detection/INSTAR_Cloud/',
        description: 'Allgemeinen Überblick über die neue Aufnahmeplattform von INSTAR. Die INSTAR Cloud bietet Ihnen sehr viele Vorteile, unter anderem z.B.: die Aufnahmen sind sicher vor Einbrechern, Sie zahlen nur für den Speicherplatz und können soviele Kameras nutzen wie Sie möchten, Alle Daten werden Sicher in deutschen Rechenzentren gespeichert, Schnelle und komfortable Übersicht über alle Alarme Ihrer Kameras, HTML5 Videos können in jedem gängigen Webbrowser ohne Videoplugins wiedergegeben werden, Laden Sie sich die Aufnahmen bequem auf Ihren PC, wesentlich kostengünstiger als eigene NVR / NAS Stationen',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/INSTAR_Cloud/Benutzer_Account_Erstellen', function(req, res) {
    res.render('./Motion_Detection/Cloud_Create_User_Account', {
        title: 'INSTAR Benutzer Account Erstellen',
        ampimg: '/images/Search/MD_SearchThumb_Cloud_Create.jpg',
        headline: 'So erstellen Sie einen neuen Account und fügen die ersten Kamera hinzu',
        breadcrumbs: '<li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/">INSTAR Cloud</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/Benutzer_Account_Erstellen/">Benutzer Account Erstellen</a></li>',
        canonical: '/Motion_Detection/INSTAR_Cloud/Create_User_Account/',
        description: 'So erstellen Sie einen neuen Account und fügen die ersten Kamera hinzu',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/INSTAR_Cloud/Speicherplatz', function(req, res) {
    res.render('./Motion_Detection/Cloud_Get_More_Cloudstorage', {
        title: 'INSTAR Cloud Speicherplatz',
        ampimg: '/images/Search/MD_SearchThumb_Cloud_Storage.jpg',
        headline: 'INSTAR Cloud - Speicherplatz kaufen und hinzubuchen',
        breadcrumbs: '<li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/">INSTAR Cloud</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/Speicherplatz/">Speicherplatz</a></li>',
        canonical: '/Motion_Detection/INSTAR_Cloud/Storage/',
        description: 'Hier erklären wir wie Sie neuen Speicherplatz in Ihre Cloud Account hinzufügen können bzw. wie Sie diesen erweitern können. Der Preis für die INSTAR Cloud, ist im Gegensatz zu vielen anderen Anbietern, nicht an die Anzahl der Kameras gebunden sondern Sie können soviele Kameras wie Sie möchten hinzufügen und zahlen nur für die Größe des Speicherplatzes den Sie verwenden möchten.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/INSTAR_Cloud/Benutzer', function(req, res) {
    res.render('./Motion_Detection/Cloud_User', {
        title: 'INSTAR Cloud Benutzerverwaltung',
        ampimg: '/images/Search/MD_SearchThumb_Cloud_Management.jpg',
        headline: 'INSTAR Cloud - Benutzer erstellen und bearbeiten von Zugriffsrechten',
        breadcrumbs: '<li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/">INSTAR Cloud</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/Benutzer/">Benutzer</a></li>',
        canonical: '/Motion_Detection/INSTAR_Cloud/User/',
        description: 'Hier zeigen wir Ihnen wie Sie zusätzliche Benutzer in Ihrem INSTAR Cloud Account hinzufügen können und diesen unterschiedliche Rechte zuweisen können. Auf diese Weise haben Sie die Möglichkeit manchen Benutzern alle Kameras anzeigen zu lassen und anderen wiederrum nur die relevanten. Gerade für Firmen ist dies interessant da Sie so unterschiedlichen Mitarbeitern Zugriff auf Ihren Account geben können ohne dabei Angst haben zu müssen, das der Benutzer irgendwelche Einstellungen verändern kann.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/INSTAR_Cloud/Administration', function(req, res) {
    res.render('./Motion_Detection/Cloud_Administration', {
        title: 'INSTAR Cloud Administration',
        ampimg: '/images/Search/MD_SearchThumb_Cloud_Administration.jpg',
        headline: 'INSTAR Cloud - Administration und Übersicht der möglichen Einstellmöglichkeiten',
        breadcrumbs: '<li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/">INSTAR Cloud</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/Administration/">Administration</a></li>',
        canonical: '/Motion_Detection/INSTAR_Cloud/Administration/',
        description: 'Hier zeigen wir Ihnen die Einstellmöglichkeiten in Ihrem INSTAR Cloud Benutzerkonto.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/INSTAR_Cloud/Alarm_Aufnahmen', function(req, res) {
    res.render('./Motion_Detection/Cloud_Alarm', {
        title: 'INSTAR Cloud Alarm Aufnahmen',
        ampimg: '/images/Search/MD_SearchThumb_Cloud_Recordings.jpg',
        headline: 'INSTAR Cloud - Alarme Ihrer IP Kameras verwalten und herunterladen',
        breadcrumbs: '<li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/">INSTAR Cloud</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/Alarm_Aufnahmen/">Alarm Aufnahmen</a></li>',
        canonical: '/Motion_Detection/INSTAR_Cloud/Alarm_Recordings/',
        description: 'Hier zeigen wir Ihnen wie man auf einfache Weise die Alarme in Ihrem INSTAR Cloud Account anschauen und verwalten kann.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

motionDetectionGerRouter.get('/INSTAR_Cloud/Kamera_Sets', function(req, res) {
    res.render('./Motion_Detection/Cloud_Sets', {
        title: 'INSTAR Cloud Sets',
        ampimg: '/images/Search/MD_SearchThumb_Cloud_Sets.jpg',
        headline: 'INSTAR Cloud - Kamera Sets erstellen und verwalten',
        breadcrumbs: '<li><a href="/Bewegungserkennung/">Bewegungserkennung</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/">INSTAR Cloud</a></li><li><a href="/Bewegungserkennung/INSTAR_Cloud/Kamera_Sets/">Kamera Sets</a></li>',
        canonical: '/Motion_Detection/INSTAR_Cloud/Camera_Sets/',
        description: 'Hier zeigen wir Ihnen wie Sie Ihre Überwachungskameras zu Sets zusammenfügen um so schnell und einfach die Aufnahmen eines kompletten Sets einsehen zu können. Dies macht vor allem dann Sinn, wenn Sie viele Kameras in Ihrem INSTAR Cloud Account hinzugefügt haben und verwalten.',
    		pacc: '',
    		ptab: 'hidden',
    		qiacc: '',
    		qitab: 'hidden',
    		mdacc: 'expanded',
    		mdtab: '',
    		iaacc: '',
    		iatab: 'hidden',
    		auacc: '',
    		autab: 'hidden',
    		hdacc: 'hidden',
    		hdtab: 'hidden',
    		fhdacc: 'hidden',
    		fhdtab: 'hidden',
    		sacc: 'hidden',
    		dlacc: 'hidden',
    		dltab: 'hidden',
      });
  });

module.exports = motionDetectionGerRouter;
